apiVersion: v1
kind: Pod

metadata:
  name: consumer
  labels:
    name: http-consumer
spec:
  restartPolicy: Never
  initContainers:
    - name: wait-seed
      image: { { $.Values.image.name } }
      imagePullPolicy: { { $.Values.image.pullPolicy } }
      command: ['/bin/sh', '-c']
      args:
        - 'until getent hosts seed.seed; do sleep 1; done; sleep 10; exit 0;'
  containers:
    - name: consumer
      image: { { $.Values.image.name } }
      imagePullPolicy: { { $.Values.image.pullPolicy } }
      command: ['node', 'consumer.js']
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SEED
          value: seed.seed
        - name: ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      ports:
        - containerPort: 8080
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: http-consumer
  labels:
    name: http-consumer
spec:
  type: NodePort
  selector:
    name: http-consumer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 30080
