apiVersion: v1
kind: Pod

metadata:
  name: seed
  labels:
    name: seed
spec:
  hostname: seed
  subdomain: seed
  containers:
    - name: seed
      image: {{$.Values.image.name}}
      imagePullPolicy: {{$.Values.image.pullPolicy}}
      command: ['node', 'seed.js']
      env:
        - name: ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: seed
spec:
  selector:
    name: seed
  clusterIP: None
