kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
