name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'
    paths:
      - '**'
  push:
    branches:
      - 'develop'
    paths:
      - '**'
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    timeout-minutes: 30
    name: CI
    steps:
      - uses: actions/checkout@v1
      - name: NPM TOKEN
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: install
        run: yarn
      - name: build
        run: yarn build
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test
      - name: doc
        run: yarn doc
      - name: publish npm
        run: bash scripts/publish.sh
        env:
          SHA: ${{ github.event.after }}
