name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'
    paths:
      - '**'
  push:
    branches:
      - 'master'
      - 'develop'
    paths:
      - '**'
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    name: CI
    steps:
      - uses: actions/checkout@v1
      #      - name: NPM TOKEN
      #        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
      - name: install
        run: |
          yarn
          yarn run build
          yarn run lint
          yarn run test
          yarn run doc
