name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'
    paths:
      - '**'
  push:
    branches:
      - 'develop'
    paths:
      - '**'
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14, 16]
    timeout-minutes: 30
    name: CI
    steps:
      - uses: actions/setup-node@v2
        with:
          # The Node.js version to configure
          node-version: ${{ matrix.node }}
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        if: ${{ matrix.node == 16 }}
        with:
          python-version: '3.8'
        env:
          PYTHON_VERSION: '3.8'
      - uses: actions/checkout@v2
      - name: NPM TOKEN
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: install
        run: yarn
      - name: build
        run: yarn build
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test
      - name: doc
        if: ${{ matrix.node == 16 }}
        run: yarn doc
      - name: publish npm
        if: ${{ matrix.node == 16 }}
        run: bash scripts/publish.sh
        env:
          SHA: ${{ github.event.after }}
