name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'
    paths:
      - '**'
  push:
    branches:
      - 'master'
      - 'develop'
    paths:
      - '**'
jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x, 15.x]
    name: install
    steps:
      - uses: actions/checkout@v1
      #      - name: NPM TOKEN
      #        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
      - name: install
        run: yarn
      - name: upload install package
        uses: actions/upload-artifact@v1
        with:
          name: scalecube-${{ matrix.node-version }}
          path: ./
  build:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    name: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: scalecube-${{ matrix.node-version }}
      - name: build
        run: yarn build
  test:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    name: test
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: scalecube-${{ matrix.node-version }}
      - name: build
        run: yarn test
  lint:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    name: lint
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: scalecube-${{ matrix.node-version }}
      - name: build
        run: yarn lint
  doc:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    name: doc
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: scalecube-${{ matrix.node-version }}
      - name: build
        run: yarn doc
